name: Build and Test

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon

      - name: Build and Test with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build test jacocoTestReport --no-daemon

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: build/reports/tests/

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: JaCoCoReport
          path: build/reports/jacoco/test/html

      - name: Upload Detekt Report
        uses: actions/upload-artifact@v4
        with:
          name: DetektReport
          path: build/reports/detekt/
